plugins {
    id "fabric-loom" version "1.6-SNAPSHOT"
}

apply from: "https://raw.githubusercontent.com/SteveKunG/GradleScripts/main/fabric.gradle"

loom {
    runs {
        client {
            if (project.hasProperty("usernameAndUUID")) {
                programArgs project.usernameAndUUID
            }
            properties project.commonProperties
            vmArgs project.commonVmArgs
        }
    }
}

String fileName = "${archives_base_name}-mc${minecraft_version}"

remapJar {
    archiveVersion = "v${project.version}"
    archiveBaseName = fileName
}