# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
java_version=25
use_mixin=true
use_access_widener=true
upload_debug=true
loom.ignoreDependencyLoomVersionValidation=true

# minecraft
minecraft_version=26.2-snapshot-6

# mod
display_name=Minecart Spawner Revived
archives_base_name=minecartspawnerrevived
mod_id=minecartspawnerrevived
mod_description=Reviving Minecart Spawner with bug fixes and small improvements!
maven_group=com.stevekung.minecartspawnerrevived
mod_version=0.0.1
release_type=release
enabled_platforms=fabric

# curseforge
curseforge_project_id=949355

# modrinth
modrinth_project_id=minecart-spawner-revived

# fabric
# https://fabricmc.net/develop/
fabric_api_version=0.148.1+26.2
fabric_loader_version=0.19.2

# neoforge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.1.2-beta