modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/SteveKunG/MinecartSpawnerRevived/issues"

[[mods]]
modId = "minecartspawnerrevived"
version = "${version}"
displayName = "Minecart Spawner Revived"
description = "Reviving Minecart Spawner with care and bug fixes!"
displayURL = "https://modrinth.com/mod/minecart-spawner-revived"
logoFile = "logo.png"
authors = "SteveKunG"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "mixins.minecartspawnerrevived.json"

[[dependencies.minecartspawnerrevived]]
modId = "minecraft"
type = "required"
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"